### KNIGHT'S WALK exercise

Creiamo la matrice

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [12]:
#Int deve sempre essere dispari
int = 7
# Crea una matrice di numeri in sequenza da 1 a num_righe * num_colonne
matrice = np.arange(1, int * int + 1).reshape(int, int)
print(matrice)


#NP.SIZE
size = np.size(matrice,0)
print(size)

#POW
min = pow(size,2)
print(min)




[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]
 [36 37 38 39 40 41 42]
 [43 44 45 46 47 48 49]]
7
49


# Scacchiera

In [19]:
def creo_scacchiera(n):                       #definisco una funzione che mi crea la scacchiera
    scacchiera = np.zeros((n*2+1,n*2+1))      #la mia scacchiera vuota
    x = n;y= n                                #centro
    scacchiera[x][y] = 1                      #imposto il centro = 1

    count = 1                                 #numero da cui parte la scacchiera
    for circle in range (n):                  #faccio partire il ciclo
        passi = 2 * (circle +1)
        x += 1
        y+= 1
        for go_up in range (passi):           #spostamento in alto
            x-=1                              #RICORDA CHE X e Y SONO LE RIGHE E COLONNE (non immaginarlo come un piano cartesiano)
            count += 1
            scacchiera [x][y]  = count
    
        for go_left in range (passi):         #spostamento a sinistra
            y-=1
            count += 1
            scacchiera [x][y] = count

        for go_down in range(passi):          #spostamento in basso
            x += 1
            count += 1
            scacchiera [x][y] = count
    
        for go_right in range (passi):        #spostamento a destra
            y += 1
            count += 1
            scacchiera [x][y] = count


    return scacchiera
    

In [30]:
#creo_scacchiera(3)
simulate_walk(creo_scacchiera(9))

([1.0,
  10.0,
  3.0,
  6.0,
  9.0,
  4.0,
  7.0,
  2.0,
  13.0,
  8.0,
  5.0,
  14.0,
  11.0,
  24.0,
  27.0,
  12.0,
  31.0,
  54.0,
  48.0,
  51.0,
  28.0,
  25.0,
  46.0,
  18.0,
  15.0,
  32.0,
  29.0,
  52.0,
  49.0,
  78.0,
  23.0,
  44.0,
  41.0,
  22.0,
  19.0,
  16.0,
  33.0,
  30.0,
  53.0,
  26.0,
  47.0,
  76.0,
  21.0,
  40.0,
  17.0,
  34.0,
  59.0,
  56.0,
  87.0,
  80.0,
  83.0,
  120.0,
  123.0,
  84.0,
  81.0,
  118.0,
  163.0,
  216.0,
  66.0,
  39.0,
  20.0,
  43.0,
  70.0,
  105.0,
  38.0,
  35.0,
  60.0,
  93.0,
  90.0,
  55.0,
  58.0,
  89.0,
  92.0,
  131.0,
  88.0,
  57.0,
  130.0,
  91.0,
  180.0,
  129.0,
  86.0,
  125.0,
  50.0,
  79.0,
  116.0,
  45.0,
  74.0,
  71.0,
  106.0,
  67.0,
  36.0,
  61.0,
  94.0,
  135.0,
  132.0,
  179.0,
  128.0,
  85.0,
  124.0,
  121.0,
  166.0,
  219.0,
  280.0,
  161.0,
  214.0,
  111.0,
  72.0,
  75.0,
  42.0,
  69.0,
  104.0,
  37.0,
  62.0,
  95.0,
  136.0,
  185.0,
  182.0,
  168.0,
  171.0,
  224.0,
  227.0,
  172.0,

Walk

In [27]:
def simulate_walk(scacchiera):
    valori=[]; coordinate_x = []; coordinate_y = []
    x = 0; y= 0
    spostamenti = ((x+2,y-1), (x+2,y+1),(x-2,y+1),(x-2,x-1),(x+1,y+2),(x+1,y-2),(x-1,y+2),(x-1,y-2)) #lista degli spostamenti possibili del cavallo
    # creo una matrice di zeri per salvare i movimenti
   
    len_scacchiera = np.size(scacchiera,0)   #ho la lunghezza della scacchiera
    max_pos = len_scacchiera//2              #ricavo il centro (doppio slash per l'approsimazione)
    visitati = np.zeros ((len_scacchiera, len_scacchiera),bool)

    #ottengo la posizione centrale
    visitati[y+max_pos, x+max_pos] = True
    valori.append(scacchiera[y+max_pos,x+max_pos]); coordinate_x.append(x); coordinate_y.append(y)    #salvare i valori nelle liste

    #MUOVIAML inizia il ciclo
    fine_gioco = False
    while not fine_gioco:
        board_min = pow(len_scacchiera,2)
        fine_gioco = True
        spostamento = ((x+2,y-1), (x+2,y+1),(x-2,y+1),(x-2,x-1),(x+1,y+2),(x+1,y-2),(x-1,y+2),(x-1,y-2))
    #check delle due scacchiere
        for test_x, test_y in spostamento:
            #abs restituisce il valore assoluto di un numero
    
            if abs(test_x)<= max_pos and abs(test_y) <= max_pos and not visitati[test_y+max_pos,test_x+max_pos]:
                test_scacchiera = scacchiera[test_y+max_pos, test_x+max_pos]
                if test_scacchiera < board_min:
                    fine_gioco = False
                    board_min = test_scacchiera; x = test_x; y = test_y

        if not fine_gioco:
            visitati[y+max_pos,x+max_pos] = True
            valori.append(board_min); coordinate_x.append(x); coordinate_y.append(y)

    return(valori, coordinate_x, coordinate_y)

In [32]:
scacchiera = creo_scacchiera(3)
display(scacchiera)

valori, coordinate_x, coordinate_y = simulate_walk(scacchiera)
print ("Sequence = ", valori)
print ("Coordinate x = ", coordinate_x)
print ("coordinate y =", coordinate_y)

array([[37., 36., 35., 34., 33., 32., 31.],
       [38., 17., 16., 15., 14., 13., 30.],
       [39., 18.,  5.,  4.,  3., 12., 29.],
       [40., 19.,  6.,  1.,  2., 11., 28.],
       [41., 20.,  7.,  8.,  9., 10., 27.],
       [42., 21., 22., 23., 24., 25., 26.],
       [43., 44., 45., 46., 47., 48., 49.]])

Sequence =  [1.0, 10.0, 3.0, 6.0, 9.0, 4.0, 7.0, 2.0, 13.0, 8.0, 5.0, 14.0, 11.0, 24.0, 27.0, 12.0, 31.0]
Coordinate x =  [0, 2, 1, -1, 1, 0, -1, 1, 2, 0, -1, 1, 2, 1, 3, 2, 3]
coordinate y = [0, 1, -1, 0, 1, -1, 1, 0, -2, 1, -1, -2, 0, 2, 1, -1, -3]


Bisognerebbe PLOTTARE I RISULTATI
ma non ho voglia, potresti farlo tu? PLEASE